### ISSUE TITLE
coredump when pegasus_bench exit

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/pegasus#204]
```
(gdb) bt
#0  0x00000000006f566c in increase_count (count=1, this=0x307d320) at /home/mi/git.xiaomi/Pegasus/pegasus/rdsn/include/dsn/tool-api/task_queue.h:85
#1  dsn::task_queue::enqueue_internal (this=0x307d320, task=0x7f3b342c4b5c) at /home/mi/git.xiaomi/Pegasus/pegasus/rdsn/src/core/core/task_queue.cpp:110
#2  0x000000000076f221 in operator() (__closure=<optimized out>, ec=...) at /home/mi/git.xiaomi/Pegasus/pegasus/rdsn/src/core/tools/common/simple_task_queue.cpp:71
#3  operator() (this=<optimized out>) at /usr/include/boost/asio/detail/bind_handler.hpp:47
#4  asio_handler_invoke<boost::asio::detail::binder1<dsn::tools::simple_timer_service::add_timer(dsn::task*)::__lambda3, boost::system::error_code> > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#5  invoke<boost::asio::detail::binder1<dsn::tools::simple_timer_service::add_timer(dsn::task*)::__lambda3, boost::system::error_code>, dsn::tools::simple_timer_service::add_timer(dsn::task*)::__lambda3>
    (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#6  boost::asio::detail::wait_handler<dsn::tools::simple_timer_service::add_timer(dsn::task*)::__lambda3>::do_complete(boost::asio::detail::io_service_impl *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=<optimized out>, base=<optimized out>) at /usr/include/boost/asio/detail/wait_handler.hpp:70
#7  0x000000000074f9cf in complete (bytes_transferred=<optimized out>, ec=..., owner=..., this=0x7f3b3405d670) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#8  do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#9  boost::asio::detail::task_io_service::run (this=0x307e220, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#10 0x000000000076eb7b in run (this=<optimized out>, ec=...) at /usr/include/boost/asio/impl/io_service.ipp:66
#11 operator() (__closure=0x30aa480) at /home/mi/git.xiaomi/Pegasus/pegasus/rdsn/src/core/tools/common/simple_task_queue.cpp:50
#12 _M_invoke<> (this=0x30aa480) at /usr/include/c++/4.8/functional:1732
#13 operator() (this=0x30aa480) at /usr/include/c++/4.8/functional:1720
#14 std::thread::_Impl<std::_Bind_simple<dsn::tools::simple_timer_service::start()::__lambda2()> >::_M_run(void) (this=0x30aa468) at /usr/include/c++/4.8/thread:115
#15 0x00007f3be2531a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007f3be278c184 in start_thread (arg=0x7f3b7b7fe700) at pthread_create.c:312
#17 0x00007f3be1c98ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)
```

**Comment by qinzuoyan** [comment]
可能是退出时对象析构的顺序问题导致的。之前为了修复内存泄露问题，对很多全局对象在退出时增加了析构操作，可以从这方面追查问题。
