### ISSUE TITLE
bug: coredump in dsn::utils::filesystem::file_tree_walk.

### ISSUE THREAD

**Issue by neverchanje** [XiaoMi/pegasus#346]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Normal bootstrap.
7/4/2019, in XiaoMi c4srv-msg cluster.

2. What did you expect to see?
No coredump.

3. What did you see instead?

```
(gdb) bt
#0  0x00007f7f8ecf51d7 in raise () from /lib64/libc.so.6
#1  0x00007f7f8ecf68c8 in abort () from /lib64/libc.so.6
#2  0x00007f7f9282f43e in dsn_coredump () at /home/wutao1/pegasus-release/rdsn/src/core/core/service_api_c.cpp:73
#3  0x00007f7f928243b4 in operator() (__closure=<optimized out>, ftwbuf=<optimized out>, typeflag=3, 
    fpath=0x47f2e000 "/home/work/ssd5/pegasus/c4srv-msg/replica/reps/10.119.pegasus/backup/backup_tmp.every_day.1562184334957.1562184336589.tmp/MANIFEST-011929")
    at /home/wutao1/pegasus-release/rdsn/src/core/core/filesystem.cpp:327
#4  std::_Function_handler<int(char const*, int, FTW*), dsn::utils::filesystem::remove_directory(const string&)::__lambda4>::_M_invoke(const std::_Any_data &, const char *, int, FTW *) (
    __functor=..., __args#0=0x47f2e000 "/home/work/ssd5/pegasus/c4srv-msg/replica/reps/10.119.pegasus/backup/backup_tmp.every_day.1562184334957.1562184336589.tmp/MANIFEST-011929", __args#1=3, 
    __args#2=<optimized out>) at /home/wutao1/app/include/c++/4.8.2/functional:2056
#5  0x00007f7f8edaa64a in process_entry () from /lib64/libc.so.6
#6  0x00007f7f8edaa97b in ftw_dir () from /lib64/libc.so.6
#7  0x00007f7f8edab13b in ftw_startup () from /lib64/libc.so.6
#8  0x00007f7f9282464e in dsn::utils::filesystem::file_tree_walk(std::string const&, std::function<int (char const*, int, FTW*)>, bool) (dirpath=..., handler=..., recursive=recursive@entry=true)
    at /home/wutao1/pegasus-release/rdsn/src/core/core/filesystem.cpp:149
#9  0x00007f7f92824de0 in remove_directory (npath=...) at /home/wutao1/pegasus-release/rdsn/src/core/core/filesystem.cpp:336
#10 dsn::utils::filesystem::remove_path (path=...) at /home/wutao1/pegasus-release/rdsn/src/core/core/filesystem.cpp:360
#11 0x00007f7f9272dbd8 in dsn::replication::replica::clear_backup_checkpoint (this=0x46dd8000, policy_name=...) at /home/wutao1/pegasus-release/rdsn/src/dist/replication/lib/replica_backup.cpp:424
#12 0x00007f7f92841609 in dsn::task::exec_internal (this=this@entry=0x55c0cc2d0) at /home/wutao1/pegasus-release/rdsn/src/core/core/task.cpp:180
#13 0x00007f7f9285529d in dsn::task_worker::loop (this=0x2867130) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:211
#14 0x00007f7f92855469 in dsn::task_worker::run_internal (this=0x2867130) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:191
#15 0x00007f7f8f64d600 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at /home/qinzuoyan/git.xiaomi/pegasus/toolchain/objdir/../gcc-4.8.2/libstdc++-v3/src/c++11/thread.cc:84
#16 0x00007f7f902c0dc5 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f7f8edb773d in clone () from /lib64/libc.so.6
```

4. What version of Pegasus are you using?
pegasus-server-1.11.5-ba0661d--release.tar.gz

**Comment by neverchanje** [comment]
Identical with #309

**Comment by neverchanje** [comment]
This bug occurred in the following code:

```cpp
static bool remove_directory(const std::string &npath)
{
    return dsn::utils::filesystem::file_tree_walk(
        npath,
        [](const char *fpath, int typeflag, struct FTW *ftwbuf) {
            bool succ;

            dassert( // ==> COREDUMP POINT
                (typeflag == FTW_F) || (typeflag == FTW_DP), "Invalid typeflag = %d.", typeflag);
            succ = (::remove(fpath) == 0);
            if (!succ) {
                dwarn("remove file %s failed, err = %s", fpath, safe_strerror(errno).c_str());
            }

            return (succ ? FTW_CONTINUE : FTW_STOP);
        },
        true);
}
```

And the server outputs:

```
F2019-07-04 04:05:56.592 (1562184356592616649 17aa3) replica.rep_long1.0404000d05dcdde3: filesystem.cpp:328:operator()(): assertion expression: (typeflag == FTW_F) || (typeflag == FTW_DP)
F2019-07-04 04:05:56.592 (1562184356592632714 17aa3) replica.rep_long1.0404000d05dcdde3: filesystem.cpp:328:operator()(): Invalid typeflag = 3.
```
