### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by neverchanje** [XiaoMi/pegasus#510]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Normal setup.

2. What did you expect to see?

No coredump.

3. What did you see instead?

```
#0  0x00007f2d945181d7 in raise () from /lib64/libc.so.6
#1  0x00007f2d945198c8 in abort () from /lib64/libc.so.6
#2  0x00007f2d984a87be in dsn_coredump () at /home/wutao1/pegasus-release/rdsn/src/core/core/service_api_c.cpp:76
#3  0x00007f2d983b2bde in dsn::replication::replica_stub::handle_log_failure (this=<optimized out>, err=...)
    at /home/wutao1/pegasus-release/rdsn/src/dist/replication/lib/replica_stub.cpp:1919
#4  0x00007f2d98361215 in dsn::replication::replica::on_append_log_completed (this=0x13c176500, mu=..., err=..., size=<optimized out>)
    at /home/wutao1/pegasus-release/rdsn/src/dist/replication/lib/replica_2pc.cpp:455
#5  0x00007f2d984bcd08 in operator() (__args#1=<optimized out>, __args#0=..., this=<optimized out>) at /home/wutao1/app/include/c++/4.8.2/functional:2464
#6  dsn::aio_task::exec (this=<optimized out>) at /home/wutao1/pegasus-release/rdsn/include/dsn/tool-api/task.h:600
#7  0x00007f2d984ba8a9 in dsn::task::exec_internal (this=this@entry=0x3c26170b2) at /home/wutao1/pegasus-release/rdsn/src/core/core/task.cpp:180
#8  0x00007f2d984cea6d in dsn::task_worker::loop (this=0x34a5b80) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:211
#9  0x00007f2d984cec39 in dsn::task_worker::run_internal (this=0x34a5b80) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:191
#10 0x00007f2d94e70600 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at /home/qinzuoyan/git.xiaomi/pegasus/toolchain/objdir/../gcc-4.8.2/libstdc++-v3/src/c++11/thread.cc:84
#11 0x00007f2d959d5dc5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f2d945da73d in clone () from /lib64/libc.so.6
```

Error logs:

```
E2020-04-05 07:09:08.766 (1586041748766408166 1ea4d) replica.default0.0000ea1200010001: mutation_log.cpp:2048:read_next_log_block(): invalid data header magic: 0x0
E2020-04-05 07:09:08.766 (1586041748766444600 1ea4d) replica.default0.0000ea1200010001: mutation_log_replay.cpp:189:replay(): replay mutation log failed: ERR_INVALID_DATA
E2020-04-05 07:09:08.768 (1586041748768574612 1ea4d) replica.default0.0000ea1200010001: replica_stub.cpp:465:initialize(): replay shared log failed, err = ERR_INVALID_DATA, time_used = 3414 ms, clear all logs ...
```

4. What version of Pegasus are you using?

> pegasus-server-1.12.1-694cbd5-glibc2.12-release

**Comment by acelyc111** [comment]
Has this bug been fixed?

**Comment by acelyc111** [comment]
Related issue: https://github.com/apache/incubator-pegasus/issues/287

**Comment by acelyc111** [comment]
https://github.com/XiaoMi/rdsn/pull/818
